name: build-windows-exe

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install deps
      run: |
        .\vcpkg\vcpkg.exe install tiff libjpeg-turbo --triplet x64-windows-static

    - name: Configure
      run: |
        cmake -S . -B build `
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake `
          -DVCPKG_TARGET_TRIPLET=x64-windows-static

    - name: Build
      run: cmake --build build --config Release

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: imgchecker-exe
        path: build/Release/*.exe
